[package]
name = "distortion-vst"
version = "0.1.0"
authors = ["Andrew Bloom <blooma116@gmail.com>"]
edition = "2018"

[dependencies]
vst = { git = "https://github.com/rustaudio/vst-rs" }

[lib]
name = "distortion_vst"
crate-type = ["cdylib"]
